import { Column, Entity, Index, JoinColumn, ManyToOne } from 'typeorm';

import { BaseEntity } from '../../../common/entities/base.entity';

import { Patient } from '../../patients/entities/patient.entity';
import { User } from '../../users/entities/user.entity';
import { SenderType } from '../enums/sender-type.enum';
import { ChatRoom } from './chat-room.entity';

/**
 * Chat message entity — stores individual messages exchanged between
 * a patient and a doctor.
 */
@Entity('chat_messages')
@Index(['patientId', 'doctorId'])
@Index(['isRead'])
@Index(['roomId', 'createdAt'])
@Index(['roomId', 'receiverId', 'isRead'])
@Index(['roomId', 'senderId', 'clientMessageId'])
export class ChatMessage extends BaseEntity {
  /** Foreign key to the room for this message. */
  @Column({ name: 'room_id', type: 'varchar', length: 32 })
  roomId!: string;

  /** Foreign key to the patient in the conversation. */
  @Column({ name: 'patient_id' })
  patientId!: string;

  /** Foreign key to the doctor (User) in the conversation. */
  @Column({ name: 'doctor_id' })
  doctorId!: string;

  /** Indicates whether the message was sent by the doctor or the patient. */
  @Column({ name: 'sender_type', type: 'enum', enum: SenderType })
  senderType!: SenderType;

  /** Sender actor ID (`users.id` or `patients.id` based on sender_type). */
  @Column({ name: 'sender_id', type: 'varchar', length: 32 })
  senderId!: string;

  /** Receiver actor ID (`users.id` or `patients.id`). */
  @Column({ name: 'receiver_id', type: 'varchar', length: 32 })
  receiverId!: string;

  /** Optional idempotency key generated by the client. */
  @Column({ name: 'client_message_id', type: 'varchar', length: 128, nullable: true })
  clientMessageId!: string | null;

  /** The message content. */
  @Column({ type: 'text' })
  message!: string;

  /** Whether the recipient has read this message. */
  @Column({ name: 'is_read', default: false })
  isRead!: boolean;

  // ──────────────────────────── Relations ────────────────────────────

  /** The room that contains this message. */
  @ManyToOne(() => ChatRoom, (room) => room.messages, {
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'room_id' })
  room!: ChatRoom;

  /** The patient participating in this conversation. */
  @ManyToOne(() => Patient, (patient) => patient.chatMessages, {
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'patient_id' })
  patient!: Patient;

  /** The doctor (User) participating in this conversation. */
  @ManyToOne(() => User, (user) => user.chatMessages, {
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'doctor_id' })
  doctor!: User;
}
